package org.sausagepan.prototyp.enums;

/**
 * Created by georg on 12.11.15.
 */
public enum ItemType {
    SMALL_SWORD, BIG_SWORD, POTION_HP, POTION_MP, SMALL_BOW, GOLDEN_BOW, KEY, FIRE_BREATH,
    ARROW_ICE, ARROW_FIRE, ARROW_WOOD, ARROW_RED, ARROW_STEEL, SWORD_KATANA, GLOVE_RED, GLOVE_SPIKE,
    BALL_FIRE, BALL_ICE, BALL_ELECTRO, BAG
}
